# Generated by Django 4.2.4 on 2023-09-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtopic',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
