# Generated by Django 4.2.4 on 2023-09-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogtopic_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTopic',
            new_name='BlogPost',
        ),
    ]
