# Generated by Django 4.2.4 on 2023-09-13 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blogtopic_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='by admin', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_post',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blogtopic',
            field=models.CharField(choices=[('World', 'World'), ('Kenya', 'Kenya'), ('Africa', 'Africa'), ('Technology', 'Technology'), ('Design', 'Design'), ('Culture', 'Culture'), ('Business', 'Business'), ('Politics', 'Politics'), ('Opinion', 'Opinion'), ('Science', 'Science'), ('Health', 'Health'), ('Style', 'Style'), ('Travel', 'Travel')], max_length=20),
        ),
    ]
